spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ljx?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ljx
    password: ${LJX_MYSQL_PASSWORD}
